{
 "title": "Heizung",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Speicher Oben",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT speicher_oben FROM solvis ORDER BY time DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Heizungspuffer Oben",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT heizungspuffer_oben FROM solvis ORDER BY time DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Heizungspuffer Unten",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT heizungspuffer_unten FROM solvis ORDER BY time DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Speicher Unten",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT speicher_unten FROM solvis ORDER BY time DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Kollektor",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT solar_kollektor FROM solvis ORDER BY time DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Solarleistung (Aktuell)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT solar_leistung FROM solvis ORDER BY time DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Solarleistung (Tag)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    TO_CHAR(time_bucket('1 day', time), 'YYYY-MM-DD') AS date,\n    integral(time_weight('linear', time, solar_leistung), 'hours')::NUMERIC(6,2) AS leistung\nFROM\n    solvis\nWHERE time >= CURRENT_DATE \nGROUP BY time_bucket('1 day', time)\nORDER BY time_bucket('1 day', time) ASC"
    }
   ]
  },
  {
   "title": "Solaranlage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT time_bucket('$__interval', time) AS time, \n  AVG(solar_kollektor) AS Kollektor, \n  AVG(solar_vorlauf) AS Vorlauf, \n  AVG(solar_ruecklauf) AS Rücklauf, \n  AVG(solar_waermetauscher) AS Wärmetauscher, \n  AVG(solar_leistung) AS Leistung \nFROM solvis \nWHERE  $__timeFilter(time)\nGROUP BY time_bucket('$__interval', time) \nORDER BY \"time\""
    }
   ]
  },
  {
   "title": "Solarleistung",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "SELECT\n    TO_CHAR(time_bucket('1 day', time, 'Europe/Vienna'), 'MM-DD') AS date,\n    (integral(time_weight('linear', time, solar_leistung), 'hours'))::NUMERIC(4,2) AS leistung\nFROM\n    solvis\nWHERE time >= CURRENT_DATE - 7 \nGROUP BY time_bucket('1 day', time, 'Europe/Vienna')\nORDER BY time_bucket('1 day', time, 'Europe/Vienna') ASC"
    }
   ]
  },
  {
   "title": "Pufferspeicher",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT time_bucket('$__interval', time) AS time, \n  AVG(speicher_oben) AS Speicher_Oben, \n  AVG(heizungspuffer_oben) AS Heizungspuffer_Oben, \n  AVG(heizungspuffer_unten) AS Heizungspuffer_Unten, \n  AVG(speicher_unten) AS Speicher_Unten,\n  AVG((speicher_oben+speicher_unten)/2) AS Durchschnitt,\n  EVERY(pumpe_heizkreis1) AS Heizkreis,\n  EVERY(durchfluss > 0) AS Warmwasser\nFROM solvis \nWHERE  $__timeFilter(time)\nGROUP BY time_bucket('$__interval', time) \nORDER BY \"time\""
    }
   ]
  },
  {
   "title": "Kesselleistung (geschätzt)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 15, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "SET max_parallel_workers_per_gather = 0;\nSELECT\n    TO_CHAR(time_bucket('1 day', time, 'Europe/Vienna'), 'MM-DD') AS date,\n    (integral(time_weight('linear', time, kessel_leistung), 'hours'))::NUMERIC(5,2) AS leistung\nFROM\n    solvis\nWHERE time >= CURRENT_DATE - 7 \nGROUP BY time_bucket('1 day', time, 'Europe/Vienna')\nORDER BY time_bucket('1 day', time, 'Europe/Vienna') ASC"
    }
   ]
  },
  {
   "title": "Kessel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT time_bucket('$__interval', time) AS time, \n  AVG(kessel) AS Kessel,\n  EVERY(kessel_ladepumpe) AS Pumpe,\n  EVERY(kessel_brenner) AS Brenner\nFROM solvis \nWHERE  $__timeFilter(time)\nGROUP BY time_bucket('$__interval', time) \nORDER BY \"time\""
    }
   ]
  },
  {
   "title": "Tagestemperaturen",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 15, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT TO_CHAR(time_bucket('1 day', time, 'Europe/Vienna'), 'MM-DD') AS date, MIN(outdoor_temperature) AS min, MAX(outdoor_temperature) AS max\nFROM weather \nWHERE time >= CURRENT_DATE - 7\nGROUP BY time_bucket('1 day', time, 'Europe/Vienna')\nORDER BY time_bucket('1 day', time, 'Europe/Vienna') ASC"
    }
   ]
  },
  {
   "title": "Solar",
   "type": "larona-epict-panel",
   "gridPos": { "h": 12, "w": 7, "x": 0, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT solar_kollektor, solar_vorlauf, solar_ruecklauf, solar_waermetauscher, solar_leistung, speicher_oben, heizungspuffer_oben, heizungspuffer_unten, speicher_unten FROM solvis ORDER BY time DESC LIMIT 1"
    },
    {
     "rawSql": "SELECT solarradiation FROM weather ORDER BY time DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Wasser",
   "type": "larona-epict-panel",
   "gridPos": { "h": 12, "w": 7, "x": 7, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT warmwasser, kaltwasser, zirkulation, durchfluss, speicher_oben, heizungspuffer_oben, heizungspuffer_unten, speicher_unten FROM solvis ORDER BY time DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Heizung",
   "type": "larona-epict-panel",
   "gridPos": { "h": 12, "w": 7, "x": 14, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT vorlauf_heizkreis1, vorlauf_heizkreis2, pumpe_heizkreis1, pumpe_heizkreis2, kessel, kessel_leistung, kessel_ladepumpe, kessel_brenner, speicher_oben, heizungspuffer_oben, heizungspuffer_unten, speicher_unten FROM solvis ORDER BY time DESC LIMIT 1"
    },
    {
     "rawSql": "SELECT outdoor_temperature, indoor_temperature FROM weather ORDER BY time DESC LIMIT 1"
    }
   ]
  }
 ]
}