{
 "title": "PV-Anlage",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Produktion",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT pv_leistung FROM senec ORDER BY time DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Verbrauch",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT hausverbrauch FROM senec ORDER BY time DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Einspeisung",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT quellen_einspeisung FROM senec ORDER BY time DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Netzbezug",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT quellen_bezug FROM senec ORDER BY time DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Laden",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT quellen_laden FROM senec ORDER BY time DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Entladen",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT quellen_entladen FROM senec ORDER BY time DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Batterie",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT batterie_soc FROM senec ORDER BY time DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Tagesproduktion",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    TO_CHAR(time_bucket('1 day', time, 'Europe/Vienna'), 'YYYY-MM-DD') AS date,\n    (integral(time_weight('linear', time, pv_leistung), 'hours'))::NUMERIC(7,0) AS leistung\nFROM\n    senec\nWHERE time >= CURRENT_DATE \nGROUP BY time_bucket('1 day', time, 'Europe/Vienna')\nORDER BY time_bucket('1 day', time, 'Europe/Vienna') ASC"
    }
   ]
  },
  {
   "title": "Tagesverbrauch",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    TO_CHAR(time_bucket('1 day', time, 'Europe/Vienna'), 'YYYY-MM-DD') AS date,\n    (integral(time_weight('linear', time, hausverbrauch), 'hours'))::NUMERIC(6,0) AS verbrauch\nFROM\n    senec\nWHERE time >= CURRENT_DATE \nGROUP BY time_bucket('1 day', time, 'Europe/Vienna')\nORDER BY time_bucket('1 day', time, 'Europe/Vienna') ASC"
    }
   ]
  },
  {
   "title": "Tageseinspeisung",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    TO_CHAR(time_bucket('1 day', time, 'Europe/Vienna'), 'YYYY-MM-DD') AS date,\n    (integral(time_weight('linear', time, quellen_einspeisung), 'hours')/1000)::NUMERIC(4,2) AS einspeisung\nFROM\n    senec\nWHERE time >= CURRENT_DATE \nGROUP BY time_bucket('1 day', time, 'Europe/Vienna')\nORDER BY time_bucket('1 day', time, 'Europe/Vienna') ASC"
    }
   ]
  },
  {
   "title": "Tagesbezug",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    TO_CHAR(time_bucket('1 day', time, 'Europe/Vienna'), 'YYYY-MM-DD') AS date,\n    (integral(time_weight('linear', time, quellen_bezug), 'hours')/1000)::NUMERIC(4,2) AS bezug\nFROM\n    senec\nWHERE time >= CURRENT_DATE \nGROUP BY time_bucket('1 day', time, 'Europe/Vienna')\nORDER BY time_bucket('1 day', time, 'Europe/Vienna') ASC"
    }
   ]
  },
  {
   "title": "Tagesladen",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    TO_CHAR(time_bucket('1 day', time, 'Europe/Vienna'), 'YYYY-MM-DD') AS date,\n    (integral(time_weight('linear', time, quellen_laden), 'hours')/1000)::NUMERIC(4,2) AS bezug\nFROM\n    senec\nWHERE time >= CURRENT_DATE \nGROUP BY time_bucket('1 day', time, 'Europe/Vienna')\nORDER BY time_bucket('1 day', time, 'Europe/Vienna') ASC"
    }
   ]
  },
  {
   "title": "Tagesentladen",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    TO_CHAR(time_bucket('1 day', time, 'Europe/Vienna'), 'YYYY-MM-DD') AS date,\n    (integral(time_weight('linear', time, quellen_entladen), 'hours')/1000)::NUMERIC(4,2) AS bezug\nFROM\n    senec\nWHERE time >= CURRENT_DATE \nGROUP BY time_bucket('1 day', time, 'Europe/Vienna')\nORDER BY time_bucket('1 day', time, 'Europe/Vienna') ASC"
    }
   ]
  },
  {
   "title": "Autonomie",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT 100*(verbrauch-bezug)/verbrauch FROM (\nSELECT\n    (integral(time_weight('linear', time, hausverbrauch), 'hours'))::NUMERIC(6,0) AS verbrauch,\n    (integral(time_weight('linear', time, quellen_bezug), 'hours'))::NUMERIC(6,0) AS bezug\nFROM\n    senec\nWHERE time >= CURRENT_DATE \nGROUP BY time_bucket('1 day', time, 'Europe/Vienna')\nORDER BY time_bucket('1 day', time, 'Europe/Vienna') DESC\n) AS data\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Produktion / Verbrauch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "SELECT time_bucket_gapfill('$__interval', time) AS time, \n  AVG(hausverbrauch) AS Verbrauch, \n  AVG(pv_leistung) AS Produktion, \n  AVG(quellen_entladen) AS Entladen\nFROM senec \nWHERE  $__timeFilter(time)\nGROUP BY time_bucket_gapfill('$__interval', time) \nORDER BY \"time\""
    },
    {
     "dataset": "wastlernet",
     "rawSql": "SELECT time, batterie_soc \nFROM senec \nWHERE  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Solarleistung",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "SELECT\n    TO_CHAR(time_bucket('1 day', time,'Europe/Vienna'), 'MM-DD') AS date,\n    (integral(time_weight('linear', time, pv_leistung), 'hours')/1000)::NUMERIC(4,2) AS leistung\nFROM\n    senec\nWHERE time >= CURRENT_DATE - 7 \nGROUP BY time_bucket('1 day', time, 'Europe/Vienna')\nORDER BY time_bucket('1 day', time, 'Europe/Vienna') ASC"
    }
   ]
  },
  {
   "title": "Autonomie",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "SELECT time_bucket_gapfill('$__interval', time) AS time, \n  LEAST(AVG(pv_leistung+quellen_entladen), AVG(hausverbrauch)) AS Eigenversorgung, \n  AVG(quellen_bezug) AS Bezug\nFROM senec \nWHERE  $__timeFilter(time)\nGROUP BY time_bucket_gapfill('$__interval', time) \nORDER BY \"time\""
    }
   ]
  },
  {
   "title": "Verbrauch",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 15, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "SELECT\n    TO_CHAR(time_bucket('1 day', time, 'Europe/Vienna'), 'MM-DD') AS date,\n    (integral(time_weight('linear', time, hausverbrauch-quellen_bezug), 'hours')/1000)::NUMERIC(4,2) AS Eigenversorgung\nFROM\n    senec\nWHERE time >= CURRENT_DATE - 7 \nGROUP BY time_bucket('1 day', time, 'Europe/Vienna')\nORDER BY time_bucket('1 day', time, 'Europe/Vienna') ASC"
    },
    {
     "rawSql": "SELECT\n    TO_CHAR(time_bucket('1 day', time, 'Europe/Vienna'), 'MM-DD') AS date,\n    (integral(time_weight('linear', time, quellen_bezug), 'hours')/1000)::NUMERIC(4,2) AS Bezug\nFROM\n    senec\nWHERE time >= CURRENT_DATE - 7 \nGROUP BY time_bucket('1 day', time, 'Europe/Vienna')\nORDER BY time_bucket('1 day', time, 'Europe/Vienna') ASC"
    }
   ]
  }
 ]
}